######################## default configuration ####################
baseURL = "https://reciclalapolitica.github.io/"
languageCode = "en-us"
title = "WishFund hugo | Nonprofit Charity Funderising Theme"
theme = "wishfund-hugo"
summaryLength = "10"
paginate = 6

[outputs]
  home = ["HTML", "AMP", "RSS", "JSON"]

######################### Plugins #################################
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "plugins/bootstrap/css/bootstrap.min.css"
  [[params.plugins.css]]
  URL = "plugins/themify/css/themify-icons.css"
  [[params.plugins.css]]
  URL = "plugins/magnific-popup/dist/magnific-popup.css"
  [[params.plugins.css]]
  URL = "plugins/slick-carousel/slick/slick.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "plugins/jquery/jquery.js"
  [[params.plugins.js]]
  URL = "plugins/bootstrap/js/bootstrap.min.js"
  [[params.plugins.js]]
  URL = "plugins/magnific-popup/dist/jquery.magnific-popup.min.js"
  [[params.plugins.js]]
  URL = "plugins/slick-carousel/slick/slick.min.js"
  [[params.plugins.js]]
  URL = "plugins/reading-time/readingTime.min.js"
  [[params.plugins.js]]
  URL = "plugins/search/fuse.min.js"
  [[params.plugins.js]]
  URL = "plugins/search/mark.js"
  [[params.plugins.js]]
  URL = "plugins/search/search.js"
  [[params.plugins.js]]
  URL = "plugins/google-map/map.js"
  
############################## navigation ###############################
[menu]
    
  [[menu.main]]
  name = "Pacto Verde"
  URL = "about"
  weight = 2
  
  [[menu.main]]
  name = "Noticias"
  URL = "#"
  weight = 3
  
  [[menu.main]]
  name = "Decálogo"
  URL = "causes"
  weight = 4

  [[menu.main]]
  weight = 5
  name = "Súmate"
  hasChildren = true

    [[menu.main]]
    parent = "Súmate"
    name = "Voluntariado"
    URL = "#"
    
    [[menu.main]]
    parent = "Súmate"
    name = "Donaciones"
    URL = "#"    
  
  [[menu.main]]
  name = "Eventos"
  URL = "#"
  weight = 6
    
  [[menu.main]]
  name = "Contacto"
  URL = "contact"
  weight = 7

  ################# footer menu ##################

  [[menu.footer]]
  name = "service"
  URL = "service"
  weight = 1

  [[menu.footer]]
  name = "Pacto Verde"
  URL = "about"
  weight = 2
  
  [[menu.footer]]
  name = "blog"
  URL = "blog"
  weight = 3
  
  [[menu.footer]]
  name = "pricing"
  URL = "pricing"
  weight = 4


[params]
logo = "images/logo.png"
home = "Inicio"
# Contact Information
phone = "+569 8 613 7390"
email = "reciclalapolitica@gmail.com"
location = "Plaza Baquedano, Providencia, Región Metropolitana"
copyright = "&copy; 2020 [Recicla la Política](#)"
# Meta data
description = "Recicla la Política - Un pacto verde para enfrentar la crisis socioecológica, climática y sanitaria."
author = "Recicla la Política"
# google map
gmapAPI = "https://maps.googleapis.com/maps/api/js?key=AIzaSyDcYmkpfUJlz82RUknm_QR07ZBtmATaViE&libraries=places"
mapLatitude = "-33.437"
mapLongitude = "-70.634"
mapMarker = "images/marker-green.png"
# Google Analitycs
googleAnalitycsID = "Your ID"

  # Preloader
  [params.preloader]
  enable = true

  # Navigation top header
  [params.topHeader]
  enable = true

  # Navigation button
  [params.navBtn]
  enable = true
  label = "Get a quote"
  link = "#"

  # Subscription
  [params.subscription]
  title = "Suscríbete"
  content = "Entérate de las últimas noticias con nuestro newsletter."
  

  #################### social icon ######################################
  [[params.social]]
  name = "Facebook"
  icon = "ti-facebook" # themify icon pack https://themify.me/themify-icons
  link = "#"
  
  [[params.social]]
  name = "Twitter"
  icon = "ti-twitter-alt" # themify icon pack https://themify.me/themify-icons
  link = "#"
  
  [[params.social]]
  name = "Instagram"
  icon = "ti-instagram" # themify icon pack https://themify.me/themify-icons
  link = "#"
  
  [[params.social]]
  name = "Youtube"
  icon = "ti-youtube" # themify icon pack https://themify.me/themify-icons
  link = "#"
  
############################# post share links ######################
[[params.postShare]]
icon = "ti-facebook" # themify icon pack https://themify.me/themify-icons
name = "facebook"
link = "#"

[[params.postShare]]
icon = "ti-twitter-alt" # themify icon pack https://themify.me/themify-icons
name = "twitter"
link = "#"

[[params.postShare]]
icon = "ti-linkedin" # themify icon pack https://themify.me/themify-icons
name = "linkedin"
link = "#"

[[params.postShare]]
icon = "ti-pinterest" # themify icon pack https://themify.me/themify-icons
name = "pinterest"
link = "#"